# Generated by Django 2.2.7 on 2019-12-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptapp', '0002_auto_20191223_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptdata',
            name='text',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
