# Generated by Django 2.2.7 on 2020-01-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptapp', '0004_auto_20191223_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptdata',
            name='original',
            field=models.CharField(blank='True', default=None, max_length=256, null=True, unique=True),
        ),
    ]
