# Generated by Django 2.2.7 on 2020-01-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryptapp', '0005_encryptdata_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryptdata',
            old_name='original',
            new_name='decrypted',
        ),
        migrations.RenameField(
            model_name='encryptdata',
            old_name='text',
            new_name='encrypted',
        ),
    ]
